# Generated by Django 2.2 on 2019-10-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_task_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
    ]
